wheel_radius :  0.063 # m
base_width :  0.45 # m
counts_per_rev : 2400
gear_ratio : 1
encoder_on_motor_shaft : 1 # 0 is false and 1 is true

pid_gains : [200,1,15]
control_rate : [50]
encoder_rate : [50]
pwm_range : [255]
no_cmd_timeout : [1]
publish_tf : true
